# Generated by Django 4.2.11 on 2024-05-12 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('cause', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Etranger',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numgr', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeExamen',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('libele_periode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SousAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_spec', models.CharField(max_length=1000, unique=True)),
                ('nom_spec_ar', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=255)),
                ('confirm_passord', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPourStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_set', to='myapp.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='StagiaireAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('gouv', models.CharField(max_length=20)),
                ('code_postal', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='categories/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idjvpo', to='myapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='ResrvationStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateTimeField()),
                ('petit_dej', models.BooleanField(default=False)),
                ('repas_midi', models.BooleanField(default=False)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='myapp.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='ResrvationEtranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateTimeField()),
                ('petit_dej', models.BooleanField(default=False)),
                ('repas_midi', models.BooleanField(default=False)),
                ('diner', models.BooleanField(default=False)),
                ('nombre_personne', models.IntegerField()),
                ('etranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_ET', to='myapp.etranger')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('validity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='myapp.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('titre_module', models.CharField(max_length=100)),
                ('nb_heure', models.IntegerField()),
                ('type', models.CharField(choices=[('Spécifique', 'Spécifique'), ('Générale', 'Générale')], max_length=100)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec1', to='myapp.specialite')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='myapp.specialite'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=6)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efv', to='myapp.matiere')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='er', to='myapp.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='categories/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ygiuo', to='myapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Abscence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_heure', models.IntegerField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rv', to='myapp.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oiev', to='myapp.periodeexamen')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eouviho', to='myapp.stagiaire')),
            ],
        ),
    ]
