# Generated by Django 4.2.11 on 2024-05-07 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etranger',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=255)),
                ('confirm_passord', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StagiaireAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('gouv', models.CharField(max_length=20)),
                ('code_postal', models.CharField(max_length=10)),
                ('code_qr', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.CharField(max_length=60000)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPourStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_set', to='myapp.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='ResrvationStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateTimeField()),
                ('petit_dej', models.BooleanField(default=False)),
                ('repas_midi', models.BooleanField(default=False)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='myapp.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='ResrvationEtranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateTimeField()),
                ('petit_dej', models.BooleanField(default=False)),
                ('repas_midi', models.BooleanField(default=False)),
                ('diner', models.BooleanField(default=False)),
                ('nombre_personne', models.IntegerField()),
                ('etranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_ET', to='myapp.etranger')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('validity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='myapp.stagiaire')),
            ],
        ),
    ]
