# Generated by Django 4.2.11 on 2024-05-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaireadmin',
            name='image',
            field=models.BinaryField(),
        ),
    ]
